[env]
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
ROOT_DIR = "{{config_root}}"

file = ".env"

[tools]
"aqua:go-task/task" = "3.42.0"
"aqua:cloudflare/cloudflared" = "2025.2.1"
"aqua:jqlang/jq" = "1.7.1"
