[env]
ROOT_DIR = "{{config_root}}"
NETWORK_DIR = "{{config_root}}/active/network"

file = ".env"

[tools]
"aqua:go-task/task" = "3.42.0"
"aqua:cloudflare/cloudflared" = "2025.2.1"
"aqua:jqlang/jq" = "1.7.1"
