services:
  cloudflared:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:2025.2.1
    restart: unless-stopped
    command: tunnel run
    networks:
      - traefik
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
