services:
  # WhoAmI - For Testing and Troubleshooting
  whoami:
    image: traefik/whoami:v1.11.0
    container_name: whoami
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - newt
    # labels:
    #   - "roll-pangolin.enable=true"
    #   - "roll-pangolin.destination=http://whoami:80"
    #   - "roll-pangolin.exposed-path=whoami.${SECRET_DOMAIN}"
