services:
  # WhoAmI - For Testing and Troubleshooting
  whoami:
    image: traefik/whoami:v1.10.4
    container_name: whoami
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "all"]
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.whoami.rule=Host(`whoami.${SECRET_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=myresolver"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

      - "traefik.constraint=proxy-public"
