services: 
 socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:1.26.2
    container_name: socket-proxy
    environment:
      - CONTAINERS=1
      - EVENTS=1
      - INFO=1
      - SERVICES=1
      - CONFIGS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet
    restart: always
    read_only: true
    tmpfs:
      - /run
