services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.19.3
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:radarr-striptracks
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /data:/data
    networks:
      - newt # port 7878
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:4.0.13
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:radarr-striptracks
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /data:/data
    networks:
      - newt # port 8989
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:1.5.1
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media
    networks:
      - newt # port 6767

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.32.2
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    restart: unless-stopped
    networks:
      - newt # port 9696
    volumes:
      - /docker/appdata/prowlarr:/config
