---
services:
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:2.5.1
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=${TIMEZONE}
    volumes:
      - /docker/appdata/jellyseer:/app/config
    restart: unless-stopped
    networks:
      - newt # Port 5055
