services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:7.4
    container_name: recyclarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - /docker/appdata/recyclarr:/config
    networks:
      - newt
