services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:7.4
    container_name: recyclarr
    security_opt: ['no-new-privileges:true']
    user: 1000:1000
    read_only: true
    tmpfs: /tmp
    volumes:
      - /docker/appdata/recyclarr:/config
    networks:
      - newt
