services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /docker/appdata/homarr:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_KEY}
      - DOCKER_HOSTNAMES=socket-proxy
      - DOCKER_PORTS=2375
    networks:
      - newt # port 7575
      - docker-proxynet
